### PR TITLE
:racehorse: Bump version

### PR DESCRIPTION
**Pull request by phedoreanu**

### CODE REVIEW

**Comment by phedoreanu** [comment]
Do you mean the Docker tags?

**Comment by markshust** [comment]
Yea, pinning out versions. So in the most recent nginx, we pinned 1.10 instead of 1.10.1. I think we should perhaps do the same thing for the php images... ?

**Comment by markshust** [comment]
Perhaps we can run automated trigger builds once we do that, so it'll auto-build out sub-pins such as 1.10.1.

**Comment by phedoreanu** [comment]
Sure, that's a good idea 👍

**Comment by markshust** [comment]
I went ahead and pinned this back at 1.10.1 for the time being. We should continue to use X.X.X format until the automated builds are in place.

I'd love things setup so that we watch nginx/php repos, and when they are updated, it triggers automated build at both X.X and X.X.X formats. I've created tickets for these:

https://github.com/mageinferno/docker-magento2-nginx/issues/7
https://github.com/mageinferno/docker-magento2-php/issues/17

**Pull request merged**
